### ISSUE TITLE
504 Timeout Leads to Bot Crashing

### ISSUE THREAD

**Issue by navi1995** [jpbberry/topgg-autoposter#7]
Hi there, I'm using autoposter to update stats to the API. However sometimes my bot runs into 504 errors with the API, which leads to the bot crashing. Is there a way to gracefully handle this?

Thanks!

```
TopGGAPIError: 504 Gateway Time-out
at Api._request (/home/bot/node_modules/@top-gg/sdk/dist/structs/Api.js:76:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Api.postStats (/home/bot/node_modules/@top-gg/sdk/dist/structs/Api.js:99:9) {
   response: Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
      [Symbol(Response internals)]: {
         url: 'https://top.gg/api/bots/stats',
         status: 504,
         statusText: 'Gateway Time-out',
         headers: [Headers],
         counter: 0
      }
   }
}
```

**Comment by navi1995** [comment]
Just a simple 
```
poster.on("error", (err) => { });
```
Woops
